### ISSUE TITLE
Generic library name cause build failure due to same name clashing

### ISSUE THREAD

**Issue by ghost** [pushbots/pushbots-react-native#3]
Hello,
I wanted to integrate this library in my project, I was already using other library so its generic library name is same as other library which I am already using i.e. `main.java.com.reactlibrary`. 
Thanks

**Comment by amrsobhy** [comment]
Can you please share crash log?

**Comment by ghost** [comment]
All I get is build failed and reason given 
`Error: more than one library with package name 'com.reactlibrary'` and i confirmed that there was one more react-native-library that had the same name, I have mentioned the same to the author or other library.

**Comment by ghost** [comment]
Hi @amrsobhy, any updates on the issue ?

**Comment by ghost** [comment]
Thanks @AbdullahDiaa  @amrsobhy :+1:
