### ISSUE TITLE
fatal error: 'React/RCTAnimationType.h' file not found

### ISSUE THREAD

**Issue by rks123941** [pushbots/pushbots-react-native#6]
For Android, everything is good but when I run for ios, got the issue.

../../react-native/React/Base/RCTConvert.h:11:9: fatal error: 'React/RCTAnimationType.h' file not found
#import <React/RCTAnimationType.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~

I'm running pushbot in react native 0.60

**Comment by AbdullahDiaa** [comment]
Have you tried rebuilding Pods? Just delete Podfile.lock, Pods, and run pod install.

**Comment by rks123941** [comment]
@AbdullahDiaa Thanks for the response. Yes, I have tried with removing Podfile.lock, Pods, and run pod install but no luck. If I want to install this plugin via pod, Podspec is needed but here I didn't saw that file. Please, can you give the support to react native 0.60? I'm stuck with here. Please help me.

Thanks in advance.

**Comment by AbdullahDiaa** [comment]
We're on it, i'll keep you updated once version is updated to support 0.60

**Comment by rks123941** [comment]
Thanks, @AbdullahDiaa. Please update as soon as possible.

**Comment by rks123941** [comment]
Hi @AbdullahDiaa, is there any update?

**Comment by AbdullahDiaa** [comment]
We're currently testing the fix.
Will keep you updated once it's deployed.

**Comment by AbdullahDiaa** [comment]
Please update to 1.1.7 
then run these commands to install the plugin:

`npm install --save @react-native-community/netinfo`

run pod install in ios folder: 
`cd ios && pod install`

**Comment by rks123941** [comment]
Thanks @AbdullahDiaa, appreciate it.
